stages:
#  - test
#  - publish
#  - deploy
  - pages


lint:
  stage: test
  image: python:3.10
  script:
    - pip install flake8 flake8-csv
    - flake8 --statistics --benchmark --doctests --format=csv_categories --tee --output-file artifacts/flake8.txt
  artifacts:
    paths:
      - artifacts
    expire_in: 30 days
  allow_failure: true

